
/*
 * This stub is generated by zrpc, DO NOT modify it!
 */

#ifndef ZRPC_ARITHMETICCLIENTSTUB_H
#define ZRPC_ARITHMETICCLIENTSTUB_H

#include <jackson/Value.h>

#include <zrpc/client/RpcClient.h>
#include <zrpc/util.h>

class ArithmeticClientStub {
public:
  ArithmeticClientStub(EventLoop *loop, const AddressOps &serverAddress)
      : client_(loop, serverAddress) {
    client_.setConnectionCallback([this](const TcpConnectionPtr &conn) {
      if (conn->connected()) {
        conn_ = conn;
        cb_(conn_);
      } else {
        assert(conn_ != nullptr);
        cb_(conn_);
      }
    });
  }

  ~ArithmeticClientStub() = default;

  void start() { client_.start(); }

  void setConnectionCallback(const ConnectionCallback &cb) { cb_ = cb; }

  void Add(double lhs, double rhs, const ResponseCallback &cb) {
    json::Value params(json::TYPE_OBJECT);

    params.addMember("lhs", lhs);

    params.addMember("rhs", rhs);

    json::Value call(json::TYPE_OBJECT);
    call.addMember("jsonrpc", "2.0");
    call.addMember("method", "Arithmetic.Add");
    call.addMember("params", params);

    assert(conn_ != nullptr);
    client_.sendCall(conn_, call, cb);
  }

  void Sub(double lhs, double rhs, const ResponseCallback &cb) {
    json::Value params(json::TYPE_OBJECT);

    params.addMember("lhs", lhs);

    params.addMember("rhs", rhs);

    json::Value call(json::TYPE_OBJECT);
    call.addMember("jsonrpc", "2.0");
    call.addMember("method", "Arithmetic.Sub");
    call.addMember("params", params);

    assert(conn_ != nullptr);
    client_.sendCall(conn_, call, cb);
  }

private:
  TcpConnectionPtr conn_;
  ConnectionCallback cb_;
  RpcClient client_;
};

#endif // ZRPC_ARITHMETICCLIENTSTUB_H
